// ============================================================
// SAMANVAY — Database Seed Data
// Replicates official mock data structure for IDRN + SACHET flows
// ============================================================

export const AGENCY_TYPES = [
  'NDRF', 'SDRF', 'Fire & Emergency Services', 'Police / Civil Defence',
  'Medical / Ambulance', 'NGO / Volunteer', 'Specialized Rescue', 'Other'
];

export const EXPERTISE_OPTIONS = [
  'Flood Rescue', 'Fire Rescue', 'Water Rescue', 'Search & Rescue',
  'Earthquake Response', 'Landslide Response', 'Cyclone Response',
  'Medical Emergency', 'Evacuation', 'Building Collapse', 'Chemical Emergency'
];

export const INITIAL_AGENCIES = [
  {
    id: 'AG-001',
    name: 'NDRF Battalion 6',
    type: 'NDRF',
    district: 'Pune',
    state: 'Maharashtra',
    phone: '+91-20-26050001',
    email: 'ndrf6.pune@ndrf.gov.in',
    status: 'AVAILABLE',
    verificationStatus: 'VERIFIED',
    verifiedAt: '2024-01-15',
    verifiedBy: 'Priya Desai (EOC)',
    coordinates: [18.5204, 73.8567],
    expertise: ['Flood Rescue', 'Search & Rescue', 'Building Collapse', 'Chemical Emergency'],
    resources: {
      personnel: { total: 120, available: 98 },
      ambulances: { total: 6, available: 5 },
      rescueVehicles: { total: 12, available: 10 },
      boats: { total: 8, available: 6 },
      drones: { total: 4, available: 4 },
      medicalKits: { total: 50, available: 45 },
    },
    address: 'NDRF Campus, Talegaon Dabhade, Pune, Maharashtra 410506',
    lastUpdated: '2 min ago',
    distance: 4.2,
    activeIncidents: 0,
    totalMissions: 134,
    establishedYear: 2009,
    about: 'National Disaster Response Force Battalion 6 is a specialized force trained in disaster response, rescue, and relief operations across western India.',
  },
  {
    id: 'AG-002',
    name: 'SDRF Unit 01',
    type: 'SDRF',
    district: 'Pune',
    state: 'Maharashtra',
    phone: '+91-20-26050002',
    email: 'sdrf.unit01.pune@maharashtra.gov.in',
    status: 'AVAILABLE',
    verificationStatus: 'VERIFIED',
    verifiedAt: '2024-02-10',
    verifiedBy: 'Vikram Rane (Collector)',
    coordinates: [18.5354, 73.8776],
    expertise: ['Flood Rescue', 'Water Rescue', 'Search & Rescue', 'Evacuation'],
    resources: {
      personnel: { total: 50, available: 32 },
      ambulances: { total: 5, available: 3 },
      rescueVehicles: { total: 4, available: 2 },
      boats: { total: 10, available: 7 },
      drones: { total: 3, available: 2 },
      medicalKits: { total: 25, available: 18 },
    },
    address: 'SDRF HQ, Shivajinagar, Pune, Maharashtra 411005',
    lastUpdated: '1 min ago',
    distance: 2.8,
    activeIncidents: 1,
    totalMissions: 89,
    establishedYear: 2012,
    about: 'State Disaster Response Force Unit 01, Maharashtra, specializing in flood rescue and water-based rescue operations in the Pune region.',
  },
  {
    id: 'AG-003',
    name: 'Pune Fire Brigade — Central',
    type: 'Fire & Emergency Services',
    district: 'Pune',
    state: 'Maharashtra',
    phone: '+91-20-26050003',
    email: 'fire.central@punecorporation.gov.in',
    status: 'LIMITED',
    verificationStatus: 'VERIFIED',
    verifiedAt: '2024-01-20',
    verifiedBy: 'Priya Desai (EOC)',
    coordinates: [18.5145, 73.8491],
    expertise: ['Fire Rescue', 'Building Collapse', 'Chemical Emergency', 'Search & Rescue'],
    resources: {
      personnel: { total: 80, available: 22 },
      ambulances: { total: 4, available: 1 },
      rescueVehicles: { total: 8, available: 3 },
      boats: { total: 2, available: 1 },
      drones: { total: 2, available: 2 },
      medicalKits: { total: 30, available: 10 },
    },
    address: 'Fire HQ, Bund Garden Road, Pune, Maharashtra 411001',
    lastUpdated: '5 min ago',
    distance: 6.1,
    activeIncidents: 2,
    totalMissions: 520,
    establishedYear: 1947,
    about: 'Pune Municipal Corporation Fire Brigade — Central Division, providing emergency fire response and urban rescue services.',
  },
  {
    id: 'AG-004',
    name: 'Mumbai NDRF Unit 3',
    type: 'NDRF',
    district: 'Mumbai',
    state: 'Maharashtra',
    phone: '+91-22-22680001',
    email: 'ndrf3.mumbai@ndrf.gov.in',
    status: 'DEPLOYED',
    verificationStatus: 'VERIFIED',
    verifiedAt: '2023-11-05',
    coordinates: [19.0760, 72.8777],
    expertise: ['Flood Rescue', 'Building Collapse', 'Cyclone Response', 'Chemical Emergency', 'Search & Rescue'],
    resources: {
      personnel: { total: 130, available: 18 },
      ambulances: { total: 8, available: 1 },
      rescueVehicles: { total: 14, available: 2 },
      boats: { total: 12, available: 2 },
      drones: { total: 6, available: 1 },
      medicalKits: { total: 60, available: 8 },
    },
    address: 'NDRF Battalion, Colaba, Mumbai, Maharashtra 400005',
    lastUpdated: '10 min ago',
    distance: 142,
    activeIncidents: 3,
    totalMissions: 280,
    establishedYear: 2009,
    about: 'National Disaster Response Force Unit 3, Mumbai — deployed for coastal and urban disaster response across Mumbai Metropolitan Region.',
  },
  {
    id: 'AG-005',
    name: 'Delhi Civil Defence Corps',
    type: 'Police / Civil Defence',
    district: 'New Delhi',
    state: 'Delhi',
    phone: '+91-11-23490001',
    email: 'civildefence@delhi.gov.in',
    status: 'AVAILABLE',
    verificationStatus: 'VERIFIED',
    verifiedAt: '2024-03-01',
    coordinates: [28.6139, 77.2090],
    expertise: ['Evacuation', 'Medical Emergency', 'Search & Rescue', 'Earthquake Response'],
    resources: {
      personnel: { total: 200, available: 180 },
      ambulances: { total: 15, available: 13 },
      rescueVehicles: { total: 10, available: 8 },
      boats: { total: 0, available: 0 },
      drones: { total: 5, available: 4 },
      medicalKits: { total: 80, available: 70 },
    },
    address: 'Civil Defence HQ, Vikas Bhawan, New Delhi 110002',
    lastUpdated: '8 min ago',
    distance: 1420,
    activeIncidents: 0,
    totalMissions: 95,
    establishedYear: 1968,
    about: 'Delhi Civil Defence Corps, dedicated to disaster relief, civilian protection, and emergency services during crises in the National Capital Region.',
  },
  {
    id: 'AG-011',
    name: 'Pimpri-Chinchwad Fire Unit',
    type: 'Fire & Emergency Services',
    district: 'Pune',
    state: 'Maharashtra',
    phone: '+91-20-27650001',
    email: 'fire@pcmc.gov.in',
    status: 'AVAILABLE',
    verificationStatus: 'PENDING',
    verifiedAt: null,
    coordinates: [18.6298, 73.7997],
    expertise: ['Fire Rescue', 'Building Collapse', 'Medical Emergency'],
    resources: {
      personnel: { total: 40, available: 38 },
      ambulances: { total: 3, available: 3 },
      rescueVehicles: { total: 5, available: 5 },
      boats: { total: 1, available: 1 },
      drones: { total: 1, available: 1 },
      medicalKits: { total: 15, available: 15 },
    },
    address: 'Fire Station, Pimpri, Pune, Maharashtra 411018',
    lastUpdated: '10 min ago',
    distance: 8.5,
    activeIncidents: 0,
    totalMissions: 0,
    establishedYear: 2020,
    about: 'Pimpri-Chinchwad Municipal Corporation Fire & Emergency Unit — pending verification for coordination network access.',
    submittedAt: '2026-08-12T06:32:00',
  }
];

export const INITIAL_INCIDENTS = [
  {
    id: 'INC-001',
    type: 'Flood',
    location: 'Sector 5, Hadapsar',
    district: 'Pune',
    severity: 'CRITICAL',
    status: 'ACTIVE',
    coordinates: [18.4950, 73.9260],
    createdAt: '2026-08-12T04:42:00',
    affectedArea: 'Sector 5, Hadapsar — 3 sq km',
    affectedPopulation: 12000,
    requiredResources: { boats: 5, ambulances: 3, personnel: 30, drones: 2 },
    assignedAgencies: ['AG-002', 'AG-003'],
    description: 'Flash flooding in Sector 5 due to heavy rainfall. Multiple residential areas inundated. Evacuation in progress.',
    timeline: [
      { time: '04:42 AM', event: 'Incident Reported', status: 'done', actor: 'System' },
      { time: '04:50 AM', event: 'Authority Notified', status: 'done', actor: 'Authority Dashboard' },
      { time: '05:10 AM', event: 'SDRF Unit 01 Identified', status: 'done', actor: 'Authority — Vikram Rane' },
      { time: '05:20 AM', event: 'Assistance Request Sent', status: 'done', actor: 'Authority — Vikram Rane' },
      { time: '05:35 AM', event: 'Request Acknowledged', status: 'done', actor: 'SDRF Unit 01' },
      { time: '06:00 AM', event: 'Resources Dispatched', status: 'done', actor: 'SDRF Unit 01' },
      { time: '06:20 AM', event: 'Operation Active', status: 'active', actor: 'On-Ground' },
      { time: 'TBD', event: 'Resolved', status: 'pending', actor: '—' },
    ],
  },
  {
    id: 'INC-002',
    type: 'Fire',
    location: 'Industrial Area, Bhosari',
    district: 'Pune',
    severity: 'HIGH',
    status: 'ACTIVE',
    coordinates: [18.6380, 73.8480],
    createdAt: '2026-08-12T08:15:00',
    affectedArea: 'Industrial Sector 4, Bhosari',
    affectedPopulation: 500,
    requiredResources: { boats: 0, ambulances: 4, personnel: 20, drones: 1 },
    assignedAgencies: ['AG-003'],
    description: 'Industrial fire at a chemical warehouse in Bhosari MIDC. Fire Brigade deployed. Hazmat risk present.',
    timeline: [
      { time: '08:15 AM', event: 'Incident Reported', status: 'done', actor: 'Emergency Control Room' },
      { time: '08:20 AM', event: 'Authority Notified', status: 'done', actor: 'System Alert' },
      { time: '08:30 AM', event: 'Pune Fire Brigade Dispatched', status: 'done', actor: 'Authority — Priya Desai' },
      { time: '08:50 AM', event: 'Fire Containment Ongoing', status: 'active', actor: 'Fire Brigade Central' },
      { time: 'TBD', event: 'Fire Extinguished', status: 'pending', actor: '—' },
      { time: 'TBD', event: 'Resolved', status: 'pending', actor: '—' },
    ],
  }
];

export const INITIAL_REQUESTS = [
  {
    id: 'REQ-1024',
    from: 'AG-002',
    fromName: 'SDRF Unit 01',
    to: 'AG-003',
    toName: 'Pune Fire Brigade — Central',
    incident: 'INC-001',
    incidentLabel: 'Flood — Sector 5',
    required: '2 Rescue Boats',
    urgency: 'IMMEDIATE',
    message: 'Additional rescue boats required at Sector 5 for evacuation of stranded civilians on rooftops.',
    status: 'DEPLOYED',
    createdAt: '2026-08-12T05:20:00',
    acknowledgedAt: '2026-08-12T05:35:00',
    deployedAt: '2026-08-12T06:00:00',
    resolvedAt: null,
    timeline: [
      { status: 'INITIATED', time: '05:20 AM', done: true },
      { status: 'ACKNOWLEDGED', time: '05:35 AM', done: true },
      { status: 'DEPLOYED', time: '06:00 AM', done: true },
      { status: 'RESOLVED', time: null, done: false },
    ],
  },
  {
    id: 'REQ-1026',
    from: 'AG-003',
    fromName: 'Pune Fire Brigade — Central',
    to: 'AG-001',
    toName: 'NDRF Battalion 6',
    incident: 'INC-002',
    incidentLabel: 'Fire — Industrial Area',
    required: '1 Chemical Response Team + HAZMAT Kit',
    urgency: 'HIGH',
    message: 'Hazardous chemical exposure risk at Bhosari warehouse fire. NDRF HAZMAT team requested immediately.',
    status: 'INITIATED',
    createdAt: '2026-08-12T08:40:00',
    acknowledgedAt: null,
    deployedAt: null,
    resolvedAt: null,
    timeline: [
      { status: 'INITIATED', time: '08:40 AM', done: true },
      { status: 'ACKNOWLEDGED', time: null, done: false },
      { status: 'DEPLOYED', time: null, done: false },
      { status: 'RESOLVED', time: null, done: false },
    ],
  }
];

export const INITIAL_RESOURCES = [
  { id: 'RES-001', name: 'Personnel', total: 895, available: 585, deployed: 310, lastUpdated: '1 min ago', icon: 'Users' },
  { id: 'RES-002', name: 'Rescue Boats', total: 87, available: 49, deployed: 38, lastUpdated: '2 min ago', icon: 'Ship' },
  { id: 'RES-003', name: 'Ambulances', total: 81, available: 51, deployed: 30, lastUpdated: '5 min ago', icon: 'Ambulance' },
  { id: 'RES-004', name: 'Rescue Vehicles', total: 92, available: 63, deployed: 29, lastUpdated: '3 min ago', icon: 'Truck' },
  { id: 'RES-005', name: 'Drones', total: 39, available: 28, deployed: 11, lastUpdated: '4 min ago', icon: 'Plane' },
  { id: 'RES-006', name: 'Medical Kits', total: 515, available: 344, deployed: 171, lastUpdated: '6 min ago', icon: 'Package' },
];

export const INITIAL_ACTIVITY = [
  { id: 1, type: 'incident', action: 'Incident CRITICAL reported', detail: 'Flood — Sector 5, Hadapsar', actor: 'System', time: '04:42 AM', severity: 'CRITICAL' },
  { id: 2, type: 'request', action: 'Assistance Request Deployed', detail: 'REQ-1024 — 2 Rescue Boats to Sector 5', actor: 'Pune Fire Brigade', time: '06:00 AM', severity: null },
  { id: 3, type: 'verification', action: 'Agency Registration Received', detail: 'Pimpri-Chinchwad Fire Unit submitted for verification', actor: 'Registration System', time: '06:32 AM', severity: null },
  { id: 4, type: 'incident', action: 'Incident HIGH reported', detail: 'Fire — Industrial Area, Bhosari', actor: 'Emergency Control Room', time: '08:15 AM', severity: 'HIGH' },
  { id: 5, type: 'system', action: 'System Operational', detail: 'SAMANVAY Node active. Multi-tier verified network online.', actor: 'SAMANVAY Core', time: '12:00 AM', severity: null },
];

export const INITIAL_NOTIFICATIONS = [
  { id: 1, type: 'alert', title: 'New Agency Registration', message: 'Pimpri-Chinchwad Fire Unit submitted for verification.', time: '10 min ago', read: false },
  { id: 2, type: 'incident', title: 'CRITICAL Incident Active', message: 'Flood at Sector 5, Hadapsar. Multi-agency rescue deployed.', time: '25 min ago', read: false },
  { id: 3, type: 'request', title: 'Request Deployed', message: 'REQ-1024 — 2 rescue boats deployed to Sector 5.', time: '2 hr ago', read: true },
];
